# Generated by Django 3.0.5 on 2020-07-26 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ponytoon', '0004_auto_20200328_0100'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logAction', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='LogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logCategory', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportCategory', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ponytoon.Comment')),
                ('post', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ponytoon.Upload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(max_length=1500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(max_length=360)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_category', to='adminpanel.ReportCategory')),
                ('relate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_upload', to='ponytoon.Upload')),
                ('relate_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_comment', to='ponytoon.Comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=20)),
                ('desc', models.TextField(blank=True, max_length=800, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logentrys_action', to='adminpanel.LogAction')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logentrys_category', to='adminpanel.LogCategory')),
                ('relate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logentrys_upload', to='ponytoon.Upload')),
                ('relate_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logentrys_comment', to='ponytoon.Comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logentrys_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
