# Generated by Django 3.0.5 on 2020-09-03 23:20

from django.db import migrations, models
import ponytoon.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200714_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/media/profile.png', upload_to='avatars', validators=[ponytoon.validators.validate_file_size]),
        ),
    ]
