# Generated by Django 3.0.5 on 2020-09-03 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200904_0120'),
    ]

    operations = [
    ]
