# Generated by Django 3.0.5 on 2020-09-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200914_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_seen',
        ),
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.IntegerField(default=0),
        ),
    ]
