# Generated by Django 3.0.5 on 2020-10-22 15:23

from django.db import migrations, models
import ponytoon.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200923_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/profile.png', upload_to='avatars', validators=[ponytoon.validators.validate_file_size]),
        ),
    ]
