# Generated by Django 3.0.5 on 2020-10-27 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201027_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezone',
            name='pyzone',
            field=models.CharField(default='Europe/Warsaw', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.ForeignKey(default='16', on_delete=django.db.models.deletion.CASCADE, to='accounts.TimeZone'),
        ),
    ]
