"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#BASE_DIR = os.path.dirname(os.path.dirname(__file__))
LOGIN_REDIRECT_URL='/'
LOGOUT_REDIRECT_URL='/'
STATIC_URL = '/static/'
STATIC_ROOT = "sttt"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/images')
MEDIA_URL = '/media/'
# MEDIA_URL = 'https://undertail-uploads.s3.eu-west-3.amazonaws.com/'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f!85pnh49#rie7mygbt_#+x*8=aa-i!)!^e%m0kg!w+k@*m8f$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.134.140']

# SECURE_SSL_REDIRECT = False
# CSRF_COOKIE_SECURE = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_HSTS_SECONDS = 10
# X_FRAME_OPTIONS = 'DENY'
# REFERRER_POLICY = 'unsafe-url'
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# SECURE_HSTS_PRELOAD = True



# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'personal',
	'ponytoon',
	'accounts',
	'adminpanel',
	'widget_tweaks',
	'django.forms',
	'el_pagination',
	'storages',
	'captcha'
	# 'channels'
]


# # # Auth
#
#
AUTHENTICATION_BACKENDS = ['accounts.backends.EmailBackend',]
AUTH_USER_MODEL = 'accounts.User'

# # # Sending Email
#
#
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = put_your_email_here
EMAIL_HOST_PASSWORD = put_your_password_here
EMAIL_PORT = 587
EMAIL_USE_SSL = False

# # # AWS configuration
#
#
AWS_ACCESS_KEY_ID = access_key_id_aws_here
AWS_SECRET_ACCESS_KEY = secret_aws_key_here
AWS_STORAGE_BUCKET_NAME = bucket_aws_name_here
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = 'public-read'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# # # Captcha settings
#
#
CAPTCHA_FOREGROUND_COLOR = '#aaa'
CAPTCHA_BACKGROUND_COLOR = '#222'
CAPTCHA_FONT_SIZE = 35
CAPTCHA_IMAGE_SIZE = (250, 50)
CAPTCHA_TIMEOUT = 2
CAPTCHA_LENGTH = 7

# # # Online status
#
#
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': ['127.0.0.1:11211']
		}
}
USER_ONLINE_TIMEOUT = 300
USER_LASTSEEN_TIMEOUT = 60 * 60 * 24 * 7


MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	# 'accounts.middleware.ActiveUserMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'templates')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.template.context_processors.media',
				'django.template.context_processors.static',
				'django.contrib.messages.context_processors.messages',
				'ponytoon.context_processors.extras',
			],
		},
	},
]

WSGI_APPLICATION = 'mysite.wsgi.application'
# ASGI_APPLICATION = 'mysite.routing.application'


# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379), ('192.168.134.135', 6379)],
#         },
#     },
# }

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql_psycopg2',
		'NAME': 'valium',
		# 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
		'USER': 'valium',
		'PASSWORD': '',
        'HOST': '',
        'PORT': '',
	}
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-GB'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
