# Generated by Django 2.2.10 on 2020-03-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_auto_20200328_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='desc',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
