# Generated by Django 3.0.5 on 2020-05-23 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponytoon', '0004_auto_20200328_0100'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel', '0004_logentry_relate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportCategory', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(max_length=360)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_category', to='adminpanel.ReportCategory')),
                ('relate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_upload', to='ponytoon.Upload')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
