# Generated by Django 3.0.5 on 2020-07-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_auto_20200714_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
