# Generated by Django 3.0.5 on 2020-07-26 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponytoon', '0004_auto_20200328_0100'),
        ('adminpanel', '0012_auto_20200726_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='comment',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ponytoon.Comment'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='post',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ponytoon.Upload'),
        ),
    ]
